version: "3.7"

########################### SERVICES
services:
  cfdns:
    image: ghcr.io/oomathurman/cfDns
    container_name: cfDns
    restart: unless-stopped
    environment:
      - domainName=
      - dnsRecords=root,*   # Use 'root' for '.domain.com'
      - apiEmail=
      - apiKey=
      - logLevel=INFO
      - cronTimer=*/5 * * * *